#pragma once

#include <protos/untrusted/Register.grpc.pb.h>
#include <protos/untrusted/Register.pb.h>


//cosmos register
class RegisterServiceImpl final : public request_proto::Register::Service
{
    
    private:
       // Example of usage:
    // Params: ServerContext: the grpc connetion context between client and server;
    //         RegisterRequest: the registration request contains trgistration information including nonce.
    // Return: RegisterResponse: the registration response contains ecc_pbkey generated by enclave and iasreport.
        virtual grpc::Status GetEngineInfo(::grpc::ServerContext* context, 
                                            const request_proto::EngineInfoRequest* request, 
                                            request_proto::EngineInfoResponse* response) override;

        uint32_t StartRemoteAttestationCosmos(request_proto::EngineInfoResponse *const register_resp);
    
};